### ISSUE TITLE
Breaks Latest Octoprint

### ISSUE THREAD

**Issue by sashasklar** [OctoPrint/OctoPrint-FirmwareUpdater#10]
Installed on latest Octoprint image, no other plugins except TouchUI. After installing FirmwareUpdater, can no longer connect to printer.

**Comment by foosel** [comment]
Cannot reproduce, please provide logs.

**Comment by ManuGithubSteam** [comment]
I can not confirm this with a Prusa i2 Mk2

**Comment by sashasklar** [comment]
Sorry for the lag in response, here's some more details:

OctoPrint: 1.3.5rc2  
Prusa i3 Mk: Firmware 3.0.11

Terminal Output:
Connecting to: /dev/ttyACM0
Changing monitoring state from 'Offline' to 'Opening serial port'
Connected to: Serial<id=0x71fe19f0, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=90.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Recv: start
Send: N0 M110 N0*125
Recv: echo:echo: Last Updated: Feb 14 2017 15:35:19 | Author: (none, default config)
Recv: Compiled: Feb 14 2017
Recv: echo: Free Memory: 2670  PlannerBufferBytes: 1280
Recv: echo:Stored settings retrieved
Recv: echo:SD init fail
There was a timeout while trying to connect to the printer
Changing monitoring state from 'Connecting' to 'Offline'
Connection closed, closing down monitor

**Comment by sashasklar** [comment]
After digging into this further, it turns out the issue was on the printer side. The z-tuning message on the Prusa MK2, which is cleared by running the V2Calibration.gcode or sending the prusa-specific G87 code, was preventing Octoprint from connecting.
