### ISSUE TITLE
Can't flash Anycubic i3 Mega

### ISSUE THREAD

**Issue by Simonv92** [OctoPrint/OctoPrint-FirmwareUpdater#100]
Hi, I'm trying to use the plugin to flash my i3 Mega with octoprint. 
I've set AVR MCU as ATmega2560 and AVR Programmer Type Arduino but the plugin always shows me "Flashing failed AVRDUDE says: 'not in sync: resp=0x00'"
What can I do?

thanks!

**Comment by benlye** [comment]
For an Atmega2560 you should use AVR Programmer Type `wiring`.

https://github.com/OctoPrint/OctoPrint-FirmwareUpdater#avrdude-configuration

If that doesn't work, post the logs.

**Comment by Simonv92** [comment]
Sorry, I already read that file but I didn't see that thing... now it works thanks!

Simone

**Comment by benlye** [comment]
Great :-)
