### ISSUE TITLE
problem with usbmount install

### ISSUE THREAD

**Issue by focussoft** [OctoPrint/OctoPrint-FirmwareUpdater#108]
**Hardware Setup**
LPC1768 SKR V1.3.

NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
octoprint 1.3.11

**Describe the problem**
pi@octopi:~ $ sudo systemctl edit systemd-udevd

Unknown operation 'edit'.

Tried upgrading systemctl , and dependencies , but didnt work

**Comment by jairuncaloth** [comment]
It doesn't look like Debian 8 (jessie) supports systemctl edit. https://manpages.debian.org/jessie/systemd/systemctl.1.en.html

On my system, Debian 9.4, that command creates a file, "/etc/systemd/system/systemd-udevd.service.d/override.conf". You could try manually creating the file and adding in the requisite lines, then continuing with the rest of the instructions. All this is doing is creating an override for systemd-udevd. You should find the default configuration at /lib/systemd/system/systemd-udevd.service. However, if you edit that file directly, next time systemd-udevd gets updated, your changes will be lost. https://wiki.debian.org/systemd#Creating_or_altering_services.

**Comment by focussoft** [comment]
i did what you suggested , but the test keeps saying "the path is not writable"

**Comment by focussoft** [comment]
UNIT                                                                      LOAD   ACTIVE SUB       DESCRIPTION
  proc-sys-fs-binfmt_misc.automount                                         loaded active waiting   Arbitrary Executable File Formats File System Automount Point
  sys-devices-platform-soc-3f201000.serial-tty-ttyAMA0-hci0-rfkill0.device  loaded active plugged   /sys/devices/platform/soc/3f201000.serial/tty/ttyAMA0/hci0/rfkill0
  sys-devices-platform-soc-3f201000.serial-tty-ttyAMA0-hci0.device          loaded active plugged   /sys/devices/platform/soc/3f201000.serial/tty/ttyAMA0/hci0
  sys-devices-platform-soc-3f201000.serial-tty-ttyAMA0.device               loaded active plugged   /sys/devices/platform/soc/3f201000.serial/tty/ttyAMA0
  sys-devices-platform-soc-3f202000.mmc-mmc_host-mmc0-mmc0:59b4-block-mmcblk0-mmcblk0p1.device loaded active plugged   /sys/devices/platform/soc/3f202000.mmc/mmc_host/mmc0/mm
  sys-devices-platform-soc-3f202000.mmc-mmc_host-mmc0-mmc0:59b4-block-mmcblk0-mmcblk0p2.device loaded active plugged   /sys/devices/platform/soc/3f202000.mmc/mmc_host/mmc0/mm
  sys-devices-platform-soc-3f202000.mmc-mmc_host-mmc0-mmc0:59b4-block-mmcblk0.device loaded active plugged   /sys/devices/platform/soc/3f202000.mmc/mmc_host/mmc0/mmc0:59b4/bl
  sys-devices-platform-soc-3f215040.serial-tty-ttyS0.device                 loaded active plugged   /sys/devices/platform/soc/3f215040.serial/tty/ttyS0
  sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.1-1\x2d1.1:1.0-net-eth0.device loaded active plugged   SMSC9512/9514 Fast Ethernet Adapter
  sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.4-1\x2d1.4:1.0-tty-ttyACM0.device loaded active plugged   Marlin_USB_Device
  sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.4-1\x2d1.4:1.2-host0-target0:0:0-0:0:0:0-block-sda-sda1.device loaded active plugged   SDCard_01 1
  sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.4-1\x2d1.4:1.2-host0-target0:0:0-0:0:0:0-block-sda.device loaded active plugged   SDCard_01
  sys-devices-platform-soc-soc:audio-bcm2835_alsa-sound-card0.device        loaded active plugged   /sys/devices/platform/soc/soc:audio/bcm2835_alsa/sound/card0
  sys-devices-virtual-net-docker0.device                                    loaded active plugged   /sys/devices/virtual/net/docker0
  sys-devices-virtual-tty-ttyprintk.device                                  loaded active plugged   /sys/devices/virtual/tty/ttyprintk
  sys-module-configfs.device                                                loaded active plugged   /sys/module/configfs
  sys-subsystem-bluetooth-devices-hci0.device                               loaded active plugged   /sys/subsystem/bluetooth/devices/hci0
  sys-subsystem-net-devices-docker0.device                                  loaded active plugged   /sys/subsystem/net/devices/docker0
  sys-subsystem-net-devices-eth0.device                                     loaded active plugged   SMSC9512/9514 Fast Ethernet Adapter
  -.mount                                                                   loaded active mounted   /
  boot.mount                                                                loaded active mounted   /boot
  dev-mqueue.mount                                                          loaded active mounted   POSIX Message Queue File System
  run-user-1000.mount                                                       loaded active mounted   /run/user/1000
  sys-kernel-config.mount                                                   loaded active mounted   Configuration File System
  sys-kernel-debug.mount                                                    loaded active mounted   Debug File System
  cups.path                                                                 loaded active waiting   CUPS Printer Service Spool
  systemd-ask-password-plymouth.path                                        loaded active waiting   Forward Password Requests to Plymouth Directory Watch
  systemd-ask-password-wall.path                                            loaded active waiting   Forward Password Requests to Wall Directory Watch
  session-c1.scope                                                          loaded active running   Session c1 of user pi
  session-c2.scope                                                          loaded active running   Session c2 of user pi
  avahi-daemon.service                                                      loaded active running   Avahi mDNS/DNS-SD Stack
  bluetooth.service                                                         loaded active running   Bluetooth service
  change_hostname.service                                                   loaded active exited    LSB: Change pi's hostname via /boot/octopi-hostname.txt
  change_password.service                                                   loaded active exited    LSB: Change pi's password via /boot/octopi-password.txt
  colord.service                                                            loaded active running   Manage, Install and Generate Color Profiles
  console-setup.service                                                     loaded active exited    LSB: Set console font and keymap
  cron.service                                                              loaded active running   Regular background program processing daemon
  cups-browsed.service                                                      loaded active running   Make remote CUPS printers available locally
  cups.service                                                              loaded active running   CUPS Printing Service
  dbus.service                                                              loaded active running   D-Bus System Message Bus
  docker.service                                                            loaded active running   Docker Application Container Engine
  dphys-swapfile.service                                                    loaded active exited    LSB: Autogenerate and use a swap file
  fake-hwclock.service                                                      loaded active exited    Restore / save the current clock
  gencert.service                                                           loaded active exited    LSB: Make sure an SSL certificate is generated for haproxy on first boot
  getty@tty1.service                                                        loaded active running   Getty on tty1
  haproxy.service                                                           loaded active running   HAProxy Load Balancer
  hciuart.service                                                           loaded active running   Configure Bluetooth Modems connected by UART
  kbd.service                                                               loaded active exited    LSB: Prepare console
  keyboard-setup.service                                                    loaded active exited    LSB: Set preliminary keymap
  kmod-static-nodes.service                                                 loaded active exited    Create list of required static device nodes for the current kernel
  networking.service                                                        loaded active exited    LSB: Raise network interfaces.
  ntp.service                                                               loaded active running   LSB: Start NTP daemon
  octoprint.service                                                         loaded active running   LSB: OctoPrint daemon
  raspi-config.service                                                      loaded active exited    LSB: Switch to ondemand cpu governor (unless shift key is pressed)
  rc-local.service                                                          loaded active running   /etc/rc.local Compatibility
  rsyslog.service                                                           loaded active running   System Logging Service
  serial-getty@ttyS0.service                                                loaded active running   Serial Getty on ttyS0
  ssh.service                                                               loaded active running   OpenBSD Secure Shell server
  systemd-fsck-root.service                                                 loaded active exited    File System Check on Root Device
  systemd-fsck@dev-mmcblk0p1.service                                        loaded active exited    File System Check on /dev/mmcblk0p1
  systemd-journald.service                                                  loaded active running   Journal Service
  systemd-logind.service                                                    loaded active running   Login Service
● systemd-modules-load.service                                              loaded failed failed    Load Kernel Modules
  systemd-random-seed.service                                               loaded active exited    Load/Save Random Seed
  systemd-remount-fs.service                                                loaded active exited    Remount Root and Kernel File Systems
  systemd-rfkill@rfkill0.service                                            loaded active exited    Load/Save RF Kill Switch Status of rfkill0
  systemd-setup-dgram-qlen.service                                          loaded active exited    Increase datagram queue length
  systemd-sysctl.service                                                    loaded active exited    Apply Kernel Variables
  systemd-tmpfiles-setup-dev.service                                        loaded active exited    Create Static Device Nodes in /dev
  systemd-tmpfiles-setup.service                                            loaded active exited    Create Volatile Files and Directories
  systemd-udev-trigger.service                                              loaded active exited    udev Coldplug all Devices
  systemd-udevd.service                                                     loaded active running   udev Kernel Device Manager
  systemd-update-utmp.service                                               loaded active exited    Update UTMP about System Boot/Shutdown
  systemd-user-sessions.service                                             loaded active exited    Permit User Sessions
  touchui.service                                                           loaded active running   LSB: TouchUI daemon
  triggerhappy.service                                                      loaded active running   LSB: triggerhappy hotkey daemon
  udev-finish.service                                                       loaded active exited    Copy rules generated while the root was ro
● usbmount@dev-sda.service                                                  loaded failed failed    usbmount@dev-sda.service
● usbmount@dev-sda1.service                                                 loaded failed failed    usbmount@dev-sda1.service
  user@1000.service                                                         loaded active running   User Manager for UID 1000
  vncserver-x11-serviced.service                                            loaded active running   VNC Server in Service Mode daemon
  webcam.service                                                            loaded active running   (null)
  webcamd.service                                                           loaded active running   LSB: webcam daemon
  -.slice                                                                   loaded active active    Root Slice
  system-getty.slice                                                        loaded active active    system-getty.slice
  system-serial\x2dgetty.slice                                              loaded active active    system-serial\x2dgetty.slice
  system-systemd\x2dfsck.slice                                              loaded active active    system-systemd\x2dfsck.slice
  system-systemd\x2drfkill.slice                                            loaded active active    system-systemd\x2drfkill.slice
  system-usbmount.slice                                                     loaded active active    system-usbmount.slice
  system.slice                                                              loaded active active    System Slice
  user-1000.slice                                                           loaded active active    user-1000.slice
  user.slice                                                                loaded active active    User and Session Slice
  avahi-daemon.socket                                                       loaded active running   Avahi mDNS/DNS-SD Stack Activation Socket
  cups.socket                                                               loaded active running   CUPS Printing Service Sockets
  dbus.socket                                                               loaded active running   D-Bus System Message Bus Socket
  docker.socket                                                             loaded active running   Docker Socket for the API
  syslog.socket                                                             loaded active running   Syslog Socket
  systemd-initctl.socket                                                    loaded active listening /dev/initctl Compatibility Named Pipe
  systemd-journald-dev-log.socket                                           loaded active running   Journal Socket (/dev/log)
  systemd-journald.socket                                                   loaded active running   Journal Socket
  systemd-shutdownd.socket                                                  loaded active listening Delayed Shutdown Socket
  systemd-udevd-control.socket                                              loaded active running   udev Control Socket
  systemd-udevd-kernel.socket                                               loaded active running   udev Kernel Socket
  var-swap.swap                                                             loaded active active    /var/swap
  basic.target                                                              loaded active active    Basic System
  bluetooth.target                                                          loaded active active    Bluetooth
  cryptsetup.target                                                         loaded active active    Encrypted Volumes
  getty.target                                                              loaded active active    Login Prompts
  local-fs-pre.target                                                       loaded active active    Local File Systems (Pre)
  local-fs.target                                                           loaded active active    Local File Systems
  multi-user.target                                                         loaded active active    Multi-User System
  network-online.target                                                     loaded active active    Network is Online
  network.target                                                            loaded active active    Network
  paths.target                                                              loaded active active    Paths
  remote-fs-pre.target                                                      loaded active active    Remote File Systems (Pre)
  remote-fs.target                                                          loaded active active    Remote File Systems
  slices.target                                                             loaded active active    Slices
  sockets.target                                                            loaded active active    Sockets
  sound.target                                                              loaded active active    Sound Card
  swap.target                                                               loaded active active    Swap
  sysinit.target                                                            loaded active active    System Initialization
  timers.target                                                             loaded active active    Timers
  systemd-tmpfiles-clean.timer                                              loaded active waiting   Daily Cleanup of Temporary Directories

**Comment by focussoft** [comment]
so i dropped the usbmount and switched to pmount and its working now
used the instructions from here : https://raspberrypi.stackexchange.com/questions/66169/auto-mount-usb-stick-on-plug-in-without-uuid/66324#66324

and here under answer 2 by papatrexas : https://raspberrypi.stackexchange.com/questions/100312/raspberry-4-usbmount-not-working
