### ISSUE TITLE
Unable to Mount SD card on LPC1798 

### ISSUE THREAD

**Issue by GhostlyCrowd** [OctoPrint/OctoPrint-FirmwareUpdater#111]
**Hardware Setup**
RE-ARM

**Describe the problem**
After following the instructions to the letter I am unable to get the SD to mount, thus the firmware path is read only

**Log Files**

Oct 24 15:16:42 octopi kernel: [  145.027930] scsi 0:0:0:0: Direct-Access     Marlin   SDCard 01        1.0  PQ: 0 ANSI: 0 CCS
Oct 24 15:16:42 octopi kernel: [  145.029653] sd 0:0:0:0: [sda] 7829504 512-byte logical blocks: (4.01 GB/3.73 GiB)
Oct 24 15:16:42 octopi kernel: [  145.031867] sd 0:0:0:0: [sda] Write Protect is off
Oct 24 15:16:42 octopi kernel: [  145.053756] sd 0:0:0:0: Attached scsi generic sg0 type 0
Oct 24 15:16:47 octopi kernel: [  150.144171] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
Oct 24 15:16:47 octopi kernel: [  150.144187] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x2 [current]
Oct 24 15:16:47 octopi kernel: [  150.144192] sd 0:0:0:0: [sda] tag#0 ASC=0x3a ASCQ=0x0
Oct 24 15:16:47 octopi kernel: [  150.144201] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 08 00
Oct 24 15:16:47 octopi kernel: [  150.149625] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
Oct 24 15:16:47 octopi kernel: [  150.149637] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x2 [current]
Oct 24 15:16:47 octopi kernel: [  150.149643] sd 0:0:0:0: [sda] tag#0 ASC=0x3a ASCQ=0x3
Oct 24 15:16:47 octopi kernel: [  150.149656] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 08 00
Oct 24 15:16:47 octopi kernel: [  150.151597] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
Oct 24 15:16:47 octopi kernel: [  150.151615] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x2 [current]
Oct 24 15:16:47 octopi kernel: [  150.151622] sd 0:0:0:0: [sda] tag#0 ASC=0x3a ASCQ=0x3
Oct 24 15:16:47 octopi kernel: [  150.151630] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 08 00
Oct 24 15:16:47 octopi kernel: [  150.151692]  sda: unable to read partition table
Oct 24 15:16:47 octopi kernel: [  150.155802] sd 0:0:0:0: [sda] Attached SCSI removable disk

**Additional context**
I'm not sure what else to try here.

**Comment by GhostlyCrowd** [comment]
Take not the Card is FAT32 and works currently to flash the firmware if i manually move the binary file to it.

**Comment by benlye** [comment]
Is it a Pi4?  Some people have had problems with usbmount and have fixed it by using a newer version.
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/issues/109

Otherwise, you need to figure out what's stopping the Pi from mounting the SD card.

**Comment by GhostlyCrowd** [comment]
No its not a Pi 4.  Thx for the link though ill check it out incase the USB mount ive installed is also an issue

**Comment by GhostlyCrowd** [comment]
I followed the Post to install the new usbmount for the Pi4 and added Privateshare=no to the service and it worked.
