### ISSUE TITLE
Documentation should state requirements clearly

### ISSUE THREAD

**Issue by IanDarwin** [OctoPrint/OctoPrint-FirmwareUpdater#128]
Only the LPC1768 method uses M997 at the moment, according to grepping the code. The doc should state, for each class of board, whether M997 is used and if not whether external hardware is needed, e.g., for a Creality Ender, does avrdude talk to a vanilla firmware or is a programming device like an ISP needed?

THanks

**Comment by benlye** [comment]
Feel free to make a pull request with any changes you think are helpful. I don't have a Creality Ender 3 so have no idea what it needs. Others with that printer have been able to use the plugin and no one had said it requires anything special.

**Comment by IanDarwin** [comment]
Done, thanks benlye.
