### ISSUE TITLE
Multiple requests to " http://sandbox.mason-tsai.com/x1mgqjg/octoprint-firmware-updater.html" being flagged as malicious by my firewall

### ISSUE THREAD

**Issue by jxlarrea** [OctoPrint/OctoPrint-FirmwareUpdater#134]
Why does this plugin make requests to " http://sandbox.mason-tsai.com/x1mgqjg/octoprint-firmware-updater.html"? My firewall reports these as "Phishing and Other Frauds website visit blocked".

Any thoughts? Is this a false positive?

**Comment by benlye** [comment]
The plugin doesn't call any external pages or sites. What makes you think it's the plugin doing it?
