### ISSUE TITLE
[Feature request] Allow flashing Prusa MK3S, full flash with language part

### ISSUE THREAD

**Issue by courtpl** [OctoPrint/OctoPrint-FirmwareUpdater#139]
The prusa MK3S has 2 commands to completely flash the firmware.
Unfortunately, this plugin can only execute one command.
Is it possible to extend the number of commands to flash a firmware?

example:

1. avrdude-slic3r -v -p atmega2560 -c wiring -P COM7 -b 115200 -D -U flash:w:0:C:\prusa3d_fw_3_9_0_MK3S\prusa3d_fw_MK3S_3_9_0_3421.hex:i
2. avrdude-slic3r -v -p atmega2560 -c arduino -P COM7 -b 115200 -D -u -U flash:w:1:C:\prusa3d_fw_3_9_0_MK3S\prusa3d_fw_MK3S_3_9_0_3421.hex:i

**Comment by benlye** [comment]
I'm working on adding a 'custom' flash method which I think would solve this for you - you could provide your own script which would run both commands.

**Comment by courtpl** [comment]
avrdude-slic3r -v -p atmega2560 -c wiring -P COM7 -b 115200 -D -flash:w:0:<drive>\<filename>:i
avrdude-slic3r -v -p atmega2560 -c arduino -P COM7 -b 115200 -D -u -U flash:w:1:<drive>\<filename>
:i
