### ISSUE TITLE
[FEATURE REQUEST] Paste into "...from file" text box.

### ISSUE THREAD

**Issue by a1b0hph0b1a** [OctoPrint/OctoPrint-FirmwareUpdater#141]
I use Visual Studio Code & Platform IO for writing Marlin (it's just soooo much faster than the Arduino IDE)

It has the feature to copy the full path of a file in the UI, see pic...

![VSC_copy_path](https://user-images.githubusercontent.com/13733356/87327094-8858ad80-c52b-11ea-8722-c8089f406d0d.png)

And, being able to paste said path directly into the plugin would be so much quicker than having to browse to the file in the dialog.

![firmware_updater_dialog](https://user-images.githubusercontent.com/13733356/87328290-2ef17e00-c52d-11ea-849d-1092ec9b8111.png)

Hope this doesn't prove to be a lot of work to implement. It's only a request and feel free free to say no. Just think it'd be stupid useful for people using VSC.

Hope you're well.

PS -  You can't drag a hex file into the window either as Octoprint thinks it's a stl / gcode file!

**Comment by benlye** [comment]
Unfortunately this isn't possible due to the way that the browser interacts with the filesystem (for security reasons).  You have to use the 'Browse' button to open the file and read the data from it.  Pretty much the same reason why #39 and #157 aren't possible either.
