### ISSUE TITLE
[FEATURE REQUEST] Arduino Uno (Atmega 328p) Support

### ISSUE THREAD

**Issue by Flihx** [OctoPrint/OctoPrint-FirmwareUpdater#143]
It would be great to be able to flash 328p-Boards for a CNC Shield for example.

**Comment by benlye** [comment]
I think you can do this easily yourself - the avrdude command line is editable in the advanced settings.  

Just change:
`{avrdude} -v -q -p {mcu} -c {programmer} -P {port} -D -C {conffile} -b {baudrate} {disableverify} -U flash:w:{firmware}:i` 

to:
`{avrdude} -v -q -p atmega328p -c {programmer} -P {port} -D -C {conffile} -b {baudrate} {disableverify} -U flash:w:{firmware}:i`

I believe you should select `arduino` as the programmer.

**Comment by Flihx** [comment]
I will try that, thank you!
