### ISSUE TITLE
Firmware icon in navbar missing

### ISSUE THREAD

**Issue by harpagophytum** [OctoPrint/OctoPrint-FirmwareUpdater#156]
Hello,
I updated the firmware and the icon appears in the navigation bar, but not correctly.

![firmware-update-icon-missing](https://user-images.githubusercontent.com/56959046/100478660-266c9f00-30ec-11eb-8981-1277d5d00f27.png)

https://fontawesome.com/v4.7.0/icon/microchip
`<i class="fa fa-microchip" aria-hidden="true"></i>`

I think it's located here.
[octoprint_firmwareupdater/templates/firmwareupdater_navbar.jinja2](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/c8902c9b5dbaa44cda6afbcfd47eb197ebb92dbc/octoprint_firmwareupdater/templates/firmwareupdater_navbar.jinja2)

`<i class="fas fa-microchip" title="Firmware Updater"></i>` 

Regards,

**Comment by benlye** [comment]
Did you enable it?

**Comment by harpagophytum** [comment]
Yes of course.
I restarted the system to.

![](https://user-images.githubusercontent.com/56959046/100478660-266c9f00-30ec-11eb-8981-1277d5d00f27.png)

How you can see, the icon is activated but its path is missing.

**Comment by harpagophytum** [comment]
don't you think the problem is here.

`- fas fa-microchip`
`+ fa fa-microchip`

**Comment by benlye** [comment]
Working fine here.
![image](https://user-images.githubusercontent.com/23322579/100481224-5a939000-30eb-11eb-9f68-fe41bb24e5e1.png)

What version of OctoPrint are you on?  I just remembered I'm on a 1.5 RC.  Will go back to stable and see if that makes a difference.

**Comment by benlye** [comment]
OK, think I found the problem.  Will need to release a new version shortly.

**Comment by benlye** [comment]
Fixed in v1.7.3.  

I had inadvertently created a dependency on Font Awesome v5, which I happen to have on my system due to another plugin I run.  Changing the syntax to `fa` instead of `fas` makes my plugin use the built-in Font Awesome v4 icons.  Will look at bundling FA5 in the future.

**Comment by harpagophytum** [comment]
Ok, Thank you for your responsiveness.
