### ISSUE TITLE
Cannot save flashing method

### ISSUE THREAD

**Issue by ravingDIODE** [OctoPrint/OctoPrint-FirmwareUpdater#164]
I am trying to use this plugin to flash my CR-10S Pro V2 and when hitting the settings button to choose the flashing method etc, it won't save the settings.

Hitting the blue save button has no effect whatsoever and closing the dialogue box doesn't save the settings either.

Is this a bug or am I missing something?

![image](https://user-images.githubusercontent.com/5293769/101125808-c782ba80-3602-11eb-82bf-73a142b26e19.png)

https://prnt.sc/vvi0oe

**Comment by benlye** [comment]
It looks like you installed the v1.7.4 pre-release. Can you try v1.7.5?

**Comment by ravingDIODE** [comment]
> It looks like you installed the v1.7.4 pre-release. Can you try v1.7.5?

How do I do that? I am using the plugin manager in OctoPrint and it seems it only detects the 1.7.3 and 1.7.4:

![image](https://user-images.githubusercontent.com/5293769/101133106-cb1d3e00-3610-11eb-97cf-512f9f1a2035.png)

**Comment by benlye** [comment]
Click the circled button:
![image](https://user-images.githubusercontent.com/23322579/101133997-9f468c00-3601-11eb-8559-00f115c7b2e7.png)

**Comment by ravingDIODE** [comment]
Strange, still gives the same...

![image](https://user-images.githubusercontent.com/5293769/101134269-c0fc3f00-3612-11eb-8c3e-0eeec3170d3f.png)

**Comment by benlye** [comment]
Try removing it and re-installing anyway.

**Comment by benlye** [comment]
There was a new release on GitHub which was tagged as a pre-release.  It seems like the Plugin Manager doesn't show pre-releases in the UI, but pulls the latest pre-release when you install.  I've removed the broken release (1.7.4) and made 1.7.5 a 'proper' release.

**Comment by ravingDIODE** [comment]
Thank you very much! Got it updated and working now.

Thanks for the quick feedback and support, really appreciate it!

**Comment by benlye** [comment]
Thanks for letting me know.
