### ISSUE TITLE
Can I flash my cr-10 ?

### ISSUE THREAD

**Issue by emanuelezambrano** [OctoPrint/OctoPrint-FirmwareUpdater#17]
Can I flash my cr-10 or I need first to modify bootloader ?

**Comment by benlye** [comment]
You will need a bootloader in order to use the plugin, as avrdude needs it to communicate with the Atmega MCU.  

I don't have any specific experience with the CR-10, but Google tells me it doesn't ship with a bootloader.  If you haven't already burned one, you'll need to do that first.
