### ISSUE TITLE
Firmware updater failing with Octoprint 1.5.1

### ISSUE THREAD

**Issue by Testmangh** [OctoPrint/OctoPrint-FirmwareUpdater#172]
**Hardware Setup**
SKR 1.3 Ender 3 PRO

**Describe the problem**
While trying to update the printers firmware it fails after the SD card is mounted on the host (I reckon).

**Log Files**
https://drive.google.com/file/d/10rQfr5qTCYhPvcjfyeOUh57dlsMaNPRT/view?usp=sharing

**Additional context**
https://i.imgur.com/eQfgs3m.png

**Comment by benlye** [comment]
Can't access your logs, but you most likely have the same problem (with sudo rights) as described/resolved in #167. 

Follow the instructions here to fix it:
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater#sudo-rights

**Comment by Testmangh** [comment]
I'm gonna try, but it was working flawlessly before updating Octoprint to version 1.5.1

**Comment by benlye** [comment]
You only *think* it was working flawlessly but an error-handling bug meant it was failing silently.

Upgrading to OctoPrint 1.5.1 also upgraded the plugin to the latest version, where it now errors when the unmount command fails.
