### ISSUE TITLE
Board TMC2208 Marlin 2x

### ISSUE THREAD

**Issue by MikeHellracer** [OctoPrint/OctoPrint-FirmwareUpdater#178]
**Hardware Setup**
TMC2208 Sovol SV02
but it is allthough used in many other Printers

**Describe the problem**
Not listesd Board

**Additional context**
please make the firmware updater compatible to that Board TMC2208

**Comment by benlye** [comment]
"TMC2208" is a stepper driver, not a controller board.

**Comment by benlye** [comment]
If this is the printer you're referring to:
https://sovol3d.com/products/sovol-sv02-dual-extrusion-3d-printer

Then the image appears to show a board with an Atmega2560 MCU, which is already supported.
