### ISSUE TITLE
board request: Anet10

### ISSUE THREAD

**Issue by mer2329** [OctoPrint/OctoPrint-FirmwareUpdater#19]
this board is included with the anet a8 and anet a6 and probably all other anet printers.
i currently use marlin-config (its here on github https://github.com/akaJes/marlin-config) 

my only issue it is a pain to move my printer near my computer every time i need to upgrade my firmware. which happens often because i am always experimenting with a new part.

**Comment by benlye** [comment]
The Anet board is already supported. Choose Atmega1284p as the MCU and Arduino as the programmer.
