### ISSUE TITLE
SKR 1.4 Turbo

### ISSUE THREAD

**Issue by Daskew78** [OctoPrint/OctoPrint-FirmwareUpdater#192]
**Hardware Setup**
BTT SKR 1.4 Turbo with Ender 5 Plus

**Describe the problem**
Sorry to post on the "Issue" thread but don't see any other way of getting in touch. There is a flash option for an LPC1768 when this is a LPC1769, I wanted to confirm selecting the LPC1768 would be okay before braking something?

**Comment by benlye** [comment]
Yes, that's the right method to use.  I've just done some documentation updates:
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md

In the latest version the option will be renamed to `lpc176x`.
