### ISSUE TITLE
skr 1.4 trubo path

### ISSUE THREAD

**Issue by blade359** [OctoPrint/OctoPrint-FirmwareUpdater#199]
the skr 1.4 trubo path for firmware /media/usb doesn't work. anything in firmware that would cause the problem? already tried SERIAL_PORT-1 & 0 maybe not the right path

**Comment by benlye** [comment]
As explained in the [documentation](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md), you need need `#define SDSUPPORT` and `#define SDCARD_CONNECTION ONBOARD`.

If you follow all the setup instructions it will work just fine.
