### ISSUE TITLE
USBasp

### ISSUE THREAD

**Issue by jammi** [OctoPrint/OctoPrint-FirmwareUpdater#20]
Please add USBasp as an option, used like `avrdude -patmega2560 -Pusb -Uflash:w:firmware.ino.hex:i`

**Comment by benlye** [comment]
Yep, that will be straightforward to add.

**Comment by benlye** [comment]
Added by https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/pull/24/commits/bc1eb13668eb6be49325225d76f00cefddd7ba02 in #24.
