### ISSUE TITLE
Howto Uninstall in terminal

### ISSUE THREAD

**Issue by carlymx** [OctoPrint/OctoPrint-FirmwareUpdater#22]
tnk

**Comment by benlye** [comment]
Not sure I follow - you want to remove the plug-in via the Linux shell?  Why not use the plugin manager?

**Comment by benlye** [comment]
You can either run the command that the plugin manager would run:
`~/OctoPrint/venv/bin/python -m pip uninstall --yes OctoPrint-FirmwareUpdater`

or remove the plugin files manually:
```
rm -rf ~/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_firmwareupdater/
rm -rf ~/OctoPrint/venv/local/lib/python2.7/site-packages/OctoPrint_FirmwareUpdater-0.2.0-py2.7.egg-info/
```
And then restart OctoPrint.

**Comment by carlymx** [comment]
Hello,

I have started a project of a new distribution to use an Orange Pi Zero as a print server with Octoprint called OrangePrint, as well as OctoPi but for the orange machine.

I found this plugin very interesting and decided to try it to include it in the Distro, I tried to install it by the command line with the command:

```
sudo apt-get update
sudo apt-get install avrdude
pip install "https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/archive/master.zip"
(Described on its website: https://plugins.octoprint.org/plugins/firmwareupdater/
```

and the result was after several restarts and updates of the explorer cache what you can see in image:

![image](https://preview.ibb.co/iAnQp6/2018_01_16.png)

The plugin did not appear in the corresponding menu and the option to uninstall it was disabled.

That's why I asked for the command to uninstall by terminal.

Using the installer that brings the Octoprint, where they leave the list of available plugins to operated in appearance without any problem.

Maybe they should look at it in case it's a bug.

Greetings and thank you.

**Comment by benlye** [comment]
OK.  I just tested and can install and remove the plugin via the command line pip command, so I'm not sure it's a bug in the plugin installer.  You must use the pip instance in the OctoPrint environment.
