### ISSUE TITLE
Help with flashing of firmware

### ISSUE THREAD

**Issue by Ruissilva** [OctoPrint/OctoPrint-FirmwareUpdater#225]
Hello,
I have a Robin Nano Board E3D.

How do i know the "path to the stm32flash binary"?

Thanks in advance

**Comment by benlye** [comment]
If you're on a Pi, and you followed the [instructions](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/stm32flash.md), it will be `/usr/bin/stm32flash`.

If you want to check you can use `which stm32flash`:

```
pi@octopi:~ $ which stm32flash
/usr/bin/stm32flash
```
