### ISSUE TITLE
Reopen #207

### ISSUE THREAD

**Issue by CornHead764** [OctoPrint/OctoPrint-FirmwareUpdater#240]
In this it's mentioned that an Ender 4.x board is needed for testing the proposed start feature. If Ender 4.x actually means Creality v4.x boards, I have a Creality V4.2.7 in my Ender 3 I'd be willing to test with. Currently with none of those additional features checked, it throws an error upon reconnection of the printer after a successful flash using the marlin binary transfer method.

https://www.creality3dofficial.com/products/creality-silent-mainboard-v4-2-7

#207

**Comment by benlye** [comment]
#207 isn't possible, as explained in #211.  For these boards you simply need to check the ''Don't wait for reset' option and you will not get an error (as explained somewhere in #190).  

I need to get around to updating the documentation...
