### ISSUE TITLE
Board Reset Failed (M997 Works)

### ISSUE THREAD

**Issue by toddwild** [OctoPrint/OctoPrint-FirmwareUpdater#243]
**Hardware Setup**
Please board type and printer make and model.

Printer: Ender 3
Mainboard: Creality 4.2.2
Current FW: Marlin 2.0.X - Bugfix
Other HW Mods: BLtouch
Octoprint Running on Pi 4 8GB

**Describe the problem**
Please provide a clear and concise description of what the problem is, including details of any error messages you receive (screenshots are helpful).

I have followed the guide here:
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md#board-reset-failed
To setup my Ender 3.
I receive octoprint error 
"Flashing failed
Board reset failed"

I have attached my firmwareupdater plugin, octoprint, and serial logs. 
[octoprint-logs.zip](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/6424397/octoprint-logs.zip)

**Log Files**
Attach the OctoPrint log and the Firmware Updater log Log files, which can be accessed under **Settings** -> **Logging** in OctoPrint, or in `~/.octoprint/logs/` on the host.  Both `octoprint.log` and `~/.octoprint/logs/plugin_firmwareupdater_console.log` should be included.

**Additional context**

Attaching my current Marlin Configuration.h and Configuration_adv.h
[Marlin_Config_Files.zip](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/6424389/Marlin_Config_Files.zip)

**Comment by benlye** [comment]
This is a known 'problem' with the Creality boards.  It's solved by checking the 'Don't wait for reset' box.

I have some documentation updates in progress which will make this part of the main doc:
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/doc-updates/doc/lpc176x.md#creality-ender-3
