### ISSUE TITLE
MarlinFTP not recognized by Plugin

### ISSUE THREAD

**Issue by Gathaeryx** [OctoPrint/OctoPrint-FirmwareUpdater#244]
**Hardware Setup**
Printer: Creality Ender3
Board: SKR Mini E3 V1.2

**Describe the problem**
The plugin keeps giving an error that the Python MBP package is not installed:
![image](https://user-images.githubusercontent.com/63103581/117136967-5c076980-ada9-11eb-8d92-b26f725513ac.png)

I have installed both the Python 2.7 and 3 versions of marlin-binary-protocol, and trying to reinstall them just gives the regular "Requirement already satisfied..." messages for both MBP and Heatshrink. 

**Log files**
[octoprint.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/6426850/octoprint.log)
[plugin_pluginmanager_console.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/6426852/plugin_pluginmanager_console.log)

**Comment by benlye** [comment]
Just a guess, but are you sure you activated the Python venv (or ran `pip` from inside the venv) when you installed the packages?

Can you post the actual commands and output from your installation attempts?

**Comment by Gathaeryx** [comment]
I feel like an idiot, you are 100% correct. I forgot to install in the virtual env.
