### ISSUE TITLE
Could not update cr-10 max, required settings needs an update

### ISSUE THREAD

**Issue by WimVDK** [OctoPrint/OctoPrint-FirmwareUpdater#255]
I'm going from stock creality hardware setup to full phase 4 bondtech DDX. This requires installing both bondtech ddx screen firmware aswell as mainboar. I've succesfully updated the LCD via the SD. I've succesfully installed AVRdude and configured it (i think). But it just wouldn't work to upload the mainboard firmware. 

Instructions say creality uses ATmega1284p and arduino programmer. The CR-10 Max seems to be an exception to that

ATMega1284p + arduino = Avrdude says: 'not in sync: resp=0x00'
ATMega1284p + wiring = Avrdude returned code 1

Succesful configuration on my CR-10 Max: ATMega2560 + wiring. So the "Required Settings" section will need an update to the example board next to ATmega2560 to specifically mention the CR-10 Max

**Comment by benlye** [comment]
Added the CR-10 max to the examples.
