### ISSUE TITLE
Settings for BigtreeTech E3 Turbo

### ISSUE THREAD

**Issue by BraveSolo** [OctoPrint/OctoPrint-FirmwareUpdater#256]
Hi, I was wondering if you knew what settings I should set the 'Flash Method' and 'AVR MCU' to for my aftermarket E3 Turbo.

**Comment by benlye** [comment]
It has an LPC1769 MCU, so you need to use either the [lpc176x](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md) or [marlinbft](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/marlinbft.md) flash method.
