### ISSUE TITLE
How to find out whether firmware includes bootloader or not?

### ISSUE THREAD

**Issue by WelliSolutions** [OctoPrint/OctoPrint-FirmwareUpdater#263]
**Hardware Setup**
i3 MK3

**Describe the problem**
The plugin says:
> Do not attempt to flash a firmware file which includes a bootloader

I downloaded a HEX file. How do I know whether or not is includes a bootloader?
The file is from Prusa: https://cdn.prusa3d.com/downloads/firmware/prusa3d_fw_3_10_0_MK3.zip

**Comment by benlye** [comment]
Most firmware files you will download do not contain a bootloader.  The warning is really there for people who compile their own firmware in the Arduino IDE, which will create two files - one with the bootloader and one without - it is important not to flash the file with `_bootloader` in its name.

I took a look at the firmware file you linked to and it does not appear to contain a bootloader.
