### ISSUE TITLE
Help flashing smt32

### ISSUE THREAD

**Issue by Ruissilva** [OctoPrint/OctoPrint-FirmwareUpdater#264]
Hello,

I have a msk e3d robin nano. I followed the steps, but now i don't know what to put in Boot0 and reset pin. Can you help?

![help](https://user-images.githubusercontent.com/77809758/125867488-2373cd64-7f66-4175-91cf-33890f0999e3.png)

**Comment by benlye** [comment]
I can't help - I don't have your board or anything like it.  Your best bet is probably to find a user group and ask there.

That said, a quick Google search says that your board can be updated via the SD card, so you should look at those methods:

LPC176x and **other boards which are updated from the SD card**
* Option 1 - [File copy using SD mount](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md)
* Option 2 - [File transfer using serial protocol](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/marlinbft.md)
