### ISSUE TITLE
Unable to select files from within iOS via Browse

### ISSUE THREAD

**Issue by TrekLurker** [OctoPrint/OctoPrint-FirmwareUpdater#266]
Under iOS 14.x and earlier, all file types are dimmed (greyed out) when attempting to select via browse. As this function calls the Files api on iOS devices, please look into addressing this in order to allow firmware updates via an Apple mobile device. Many thanks!

**Comment by benlye** [comment]
There is a setting in the plugin options to disable file filters which is supposed to solve this problem.  Have you tried it?

![image](https://user-images.githubusercontent.com/23322579/127269540-031f51ef-c9e5-4dc8-9e39-e34584819d9b.png)
