### ISSUE TITLE
Feature request: Create differente profiles.

### ISSUE THREAD

**Issue by SinisterRj** [OctoPrint/OctoPrint-FirmwareUpdater#269]
I'm using this plugin to flash my arduino and it's very usefull, but every time i need to flash my printer i need to configure everything again. So, my suggestions is to create configuration "profiles", where user can save all the configuration on "plugin configuration" tabs for more than one device and name it. It will be handfull for people that have more than one printer also.

**Comment by benlye** [comment]
Feature already exists, you just need to enable it...
![image](https://user-images.githubusercontent.com/23322579/127823992-ef0291df-d2e9-455c-a8e9-913dfb35133b.png)
