### ISSUE TITLE
Disconnect the printer or dont send the firmware

### ISSUE THREAD

**Issue by Alissonverd** [OctoPrint/OctoPrint-FirmwareUpdater#27]
Hello,
We need to add a printer connection check before sending the firmware. 
If the printer is connected or the USB is busy, we get an error message when sending the firmware and after difficulties in disconnecting and reconnecting.

Thank you

**Comment by benlye** [comment]
Please explain further. 

If the printer is connected it will be disconnected automatically. It's always worked for me.

Can you attach the relevant part of the OctoPrint log?

Are you running the latest version, 0.4.0? The initial release had an issue when the connection was set to AUTO.

**Comment by Alissonverd** [comment]
![firmware_update](https://user-images.githubusercontent.com/35609430/35413610-25f6187e-0207-11e8-89d4-26ad9652c59f.png)
If the printer in "State: Operational" and you send the firmware.. we have this msg.. and problems after it.

**Comment by benlye** [comment]
Please update to the latest version.

**Comment by Alissonverd** [comment]
I will install the last version and test. I dont receive any order to update the plugin.

**Comment by Alissonverd** [comment]
So. See the problem with bootloader files.. 
It took my sleep for a whole night. haha

**Comment by benlye** [comment]
Yes, I saw that too. Still  thinking about how to address it... Not sure what I can do other than adding a warning not to flash files that include a bootloader.

**Comment by Alissonverd** [comment]
Maybe only check the file name in first time and stop proccess.

**Comment by Alissonverd** [comment]
The new version working fine. Disconnect, flash and reconnect!
I will use the post-flash gcode.

Sorry for dont check the version.
Amazing work! thank you!

**Comment by benlye** [comment]
:-)
