### ISSUE TITLE
Firmware Update Support for Voxelab Aquila G32

### ISSUE THREAD

**Issue by K0LL3KT0R** [OctoPrint/OctoPrint-FirmwareUpdater#271]
**Hardware Setup**
Voxelab Aquila G32 board with STM32 processor

**Describe the problem**
There's no clear instructions or notations anywhere regarding the Voxelab Aquila which is a clone of the Ender 3 v2, which I also didn't see instructions for. Different board than the standard Ender 3 and 3 Pro. 

**Log Files**

**Additional context**
The SD slot on my Aquila is broken - therefore, my option to upgrade/update firmware is limited to doing it via USB or Octoprint. All instructions I could find regarding the 3 v2 only reference accessing the SD card via Octoprint, not upgrading directly via a file on my computer using the Octoprint plugin. 

There are apparently at least 3 different boards for the Aquila at this time - the G32, an H32, and an N32. The G32 is the most prevalent and is a clone of the E3v2 with original ARM chip. But some of them DO also use GD32 chip clones with lower onboard memory.

**Comment by benlye** [comment]
The Ender 3 v2 is updated via the SD card and has been covered here in several issues (e.g. #190) - it can be updated using the MarlinBFT method.

If your board is a clone of the Ender 3 V2 and is normally updated via the SD card then it's quite likely there isn't another feasible way to do it as updating relies on flashing the firmware image from the SD card.

Also, I can only write instructions for boards I have, which is a pretty short list.  For anything else I rely on people with the board to contribute.

Realistically, you have three options:
1. Figure it out for yourself and then help to update the documentation
2. Find a user group for your printer/board and get help there (and then help to update the documentation)
3. Send me a board and I can try to figure it out
