### ISSUE TITLE
Firmware Flashing for Geeetech 

### ISSUE THREAD

**Issue by mitchbw** [OctoPrint/OctoPrint-FirmwareUpdater#273]
Hi, would love to use this. 
can you update for use with Geeetech's family of printers, notably the A10 A10M A20 A20M A20T running Marlin (in my case Marlin 1.1.7 but hoping to update to the latest compatible version)
Newish to 3D printers but happy to supply more info if required 

Regards, 
M

**Comment by benlye** [comment]
A quick google search says that that those printers are updated using Arduino / avrdude, so you should just be able to follow the [avrdude instructions](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/avrdude.md).

**Comment by mitchbw** [comment]
okay thanks ☺️ I did not realise.

there's a lot to take it when starting out,

Would appreciate it being added to the list 😊

fab work BTW, i certainly would be thinking more than twice about updating
firmware if having to do it in a more involved manner, this looks like it
intends to take care a lot of the hard and confusing aspects

-----
Mitchell Bradley-Williams
