### ISSUE TITLE
Anycubic i3 Mega S

### ISSUE THREAD

**Issue by wassereimer86** [OctoPrint/OctoPrint-FirmwareUpdater#276]
Hello,

perhaps i´m not able to find the info: But do you support this printer? And what  are the settings? The hole options don´t tell my anything. 👀

Best regards
Jens

**Comment by YOTV** [comment]
Try this command

sudo apt-get install avrdude

**Comment by wassereimer86** [comment]
As i wrote: It´s already installed in Docker. But it´s not documented or i couldn´t find the information.
