### ISSUE TITLE
Will this work with a Prusa i3 mk3s+?

### ISSUE THREAD

**Issue by DarumasLegs** [OctoPrint/OctoPrint-FirmwareUpdater#278]
**Hardware Setup**
Curious if this will work with the Prusa i3 mk3s+. I see that it supports the Prusa MMU, but what about the printer?

**Comment by benlye** [comment]
Yes, I believe it should work.

**Comment by Samaelson** [comment]
@DarumasLegs : Yes, MMU2 Unit needs to be connected via MicroUSB cable.
