### ISSUE TITLE
Flash issue with marlinbft and Ender 3 Pro with 4.2.7 motherboard

### ISSUE THREAD

**Issue by coliss86** [OctoPrint/OctoPrint-FirmwareUpdater#281]
**Hardware Setup**
- Ender 3 Pro
- Motherboard : Creality v4.2.7
- Marlin 2.0.9.2, compiled from https://gitlab.com/coliss86/marlin-2.x.
Here is a `M115`: 

```
Send: M115
Recv: FIRMWARE_NAME:Marlin 2.0.9.2 (Oct 29 2021 10:30:37) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Custom EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Recv: Cap:SERIAL_XON_XOFF:0
Recv: Cap:BINARY_FILE_TRANSFER:1
Recv: Cap:EEPROM:1
Recv: Cap:VOLUMETRIC:1
Recv: Cap:AUTOREPORT_POS:0
Recv: Cap:AUTOREPORT_TEMP:1
Recv: Cap:PROGRESS:0
Recv: Cap:PRINT_JOB:1
Recv: Cap:AUTOLEVEL:1
Recv: Cap:RUNOUT:0
Recv: Cap:Z_PROBE:1
Recv: Cap:LEVELING_DATA:1
Recv: Cap:BUILD_PERCENT:0
Recv: Cap:SOFTWARE_POWER:0
Recv: Cap:TOGGLE_LIGHTS:0
Recv: Cap:CASE_LIGHT_BRIGHTNESS:0
Recv: Cap:EMERGENCY_PARSER:0
Recv: Cap:HOST_ACTION_COMMANDS:1
Recv: Cap:PROMPT_SUPPORT:1
Recv: Cap:SDCARD:1
Recv: Cap:REPEAT:0
Recv: Cap:SD_WRITE:1
Recv: Cap:AUTOREPORT_SD_STATUS:0
Recv: Cap:LONG_FILENAME:0
Recv: Cap:THERMAL_PROTECTION:1
Recv: Cap:MOTION_MODES:0
Recv: Cap:ARCS:1
Recv: Cap:BABYSTEPPING:1
Recv: Cap:CHAMBER_TEMPERATURE:0
Recv: Cap:COOLER_TEMPERATURE:0
Recv: Cap:MEATPACK:0
```

**Describe the problem**
I followed the [doc to flash the printer with marlinbft](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/marlinbft.md). When the SD Card is empty, the printer is successfully flashed. However, when I repeated the process, the updater tells me that the printer has been successfully flashed but I cannot see my updates on the printer.
I plug the SD card to my computer and found the previous firmware.
Here the content of the SD Card : 
![image](https://user-images.githubusercontent.com/23615562/139411122-2aff95b6-7d64-4522-b6e1-fa14d10f1447.png)

**Log Files**
[flash.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/7440693/flash.log)

**Additional context**
Here is the setup of the plugin : 
![image](https://user-images.githubusercontent.com/23615562/139411287-35a5126d-4328-40b4-bd21-1fca10f6f59f.png)

![image](https://user-images.githubusercontent.com/23615562/139411302-4af57f77-1245-464e-b22d-734e3677fd24.png)

**Comment by coliss86** [comment]
Here is what I have done : 
- flash two times with success and eject the SD card to check the content. Only the file `fw102613.bin` was present in it.
- flash another time with success but the printer keep restarting until I unplug the sdcard ?!?! We can see it with the following lines :
```
2021-10-30 10:30:52,440 - octoprint.plugins.action_command_notification - INFO - Got a notification: GMEEEE Ready.
2021-10-30 10:31:00,417 - octoprint.plugins.action_command_notification - INFO - Got a notification: GMEEEE Ready.
2021-10-30 10:31:08,395 - octoprint.plugins.action_command_notification - INFO - Got a notification: GMEEEE Ready.
2021-10-30 10:31:16,373 - octoprint.plugins.action_command_notification - INFO - Got a notification: GMEEEE Ready.
2021-10-30 10:31:24,355 - octoprint.plugins.action_command_notification - INFO - Got a notification: GMEEEE Ready.
```
- flash a last time with success. But the file still present on the sd card is `fw103017.bin` from the third flash attempt.

Is it possible to add an option which deletes all the files `fw.*\.bin` before starting to flash ?

[here are the logs](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/7446159/octoprint.log)
Tell me if you want me to do new tests.

**Comment by benlye** [comment]
If you were able to flash twice in a row successfully, and only the last used file was present on the card, then it seems like the plugin is working correctly.  The FW file uploaded/flashed last won't be deleted until you attempt to update using the plugin again.

I don't know why the board would keep resetting until the card was removed, that's not a problem I've seen before but it sounds like something went wrong with the board's internal updating process.

**Comment by coliss86** [comment]
Ok, I'm closing the issue until the next problem :-) 

Thanks for your help :muscle:
