### ISSUE TITLE
Saving options never ends

### ISSUE THREAD

**Issue by ARU64** [OctoPrint/OctoPrint-FirmwareUpdater#291]
**Hardware Setup**
Please board type and printer make and model.
Rambo on Prusa i3 MK3S
**Describe the problem**
Please provide a clear and concise description of what the problem is, including details of any error messages you receive (screenshots are helpful).
When saving the options in the addon, the saving seems to never end (wheels of dots on save button).
**Log Files**
Attach the OctoPrint log and the Firmware Updater log Log files, which can be accessed under **Settings** -> **Logging** in OctoPrint, or in `~/.octoprint/logs/` on the host.  Both `octoprint.log` and `~/.octoprint/logs/plugin_firmwareupdater_console.log` should be included.

**Additional context**
[octoprint.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/7784500/octoprint.log)
[plugin_firmwareupdater_console (1).log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/7784501/plugin_firmwareupdater_console.1.log)
<img width="564" alt="Screenshot 2021-12-28 at 12 44 51" src="https://user-images.githubusercontent.com/49149180/147563843-50ced390-d843-4eb5-af16-3e1be6f0f0e6.png">

**Comment by benlye** [comment]
Most likely a browser issue. Try a full refresh of the page with Ctrl+F5 or clearing your cache if that doesn't work.
