### ISSUE TITLE
[INFORMATION] configuration.h Information for nxp hardware 

### ISSUE THREAD

**Issue by njozsef** [OctoPrint/OctoPrint-FirmwareUpdater#292]
**Hardware Setup**
MKS sgen l v1.0

**Describe the problem**
Need comment in configuration.h for working  in MKS sgen l v1.0  board.
//#define SD_CHECK_AND_RETRY

**Log Files**
-

**Additional context**
-

**Comment by benlye** [comment]
Presumably this is for the lpc176x update method?
