### ISSUE TITLE
mainboard hinzufügen 

### ISSUE THREAD

**Issue by Seroga23** [OctoPrint/OctoPrint-FirmwareUpdater#295]
hallo 
könnten sie bitte das board bigtreetech octopus 1.1 hinzufügen damit ich es updaten kann 
es hat einen 32-Bit ARM Cortex-M4 CPU mit 180MHz 
 Danke :)

**Comment by benlye** [comment]
No need for me to add anything - you can update the firmware on that board by copying a file named `firmware.bin` to the SD card, so you have the choice of using either the [lpc176x](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md) or [marlinbft](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/marlinbft.md) methods.
