### ISSUE TITLE
Post-flash system command disappears in v1.13.0

### ISSUE THREAD

**Issue by reichhartkg** [OctoPrint/OctoPrint-FirmwareUpdater#296]
Enter `date > /tmp/firmware_update_start` in "Pre-flash system command" and the command is executed.  When you leave prefs and go back in, the box is still checked and the command is still in the text field.

Enter `date > /tmp/firmware_update_end` in "Post-flash system command" and the command is not executed.  When you leave prefs and go back in, the box is still checked but the text field is empty.

**Comment by benlye** [comment]
Fixed in v1.13.1.
