### ISSUE TITLE
[Informational] Can the plugin flash both Marlin and Klipper?

### ISSUE THREAD

**Issue by jsdokos** [OctoPrint/OctoPrint-FirmwareUpdater#297]
**Hardware Setup**
Ender 3 (heavily modified)
BTT SKR Mini E3 V2.0

**Describe the problem**
I am using the [lpc176x](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md) method to flash my board now. I have looked around, and I can't tell if I can flash a generic firmware, or it has to be marlin. I went through old issues, and it seems like yes, but I'd like to not brick my board if possible.

**Log Files**
N/A

**Additional context**
#252 would imply that you can, but i'm not sure

**Comment by benlye** [comment]
I've no idea, I've never used Klipper. It works great with Marlin.

**Comment by jsdokos** [comment]
I've been using it for Marlin for a while, so I may just need to bite the bullet and try it. I'll try and report back, but close this for now.
