### ISSUE TITLE
Major Fault in Logging

### ISSUE THREAD

**Issue by CmdrCody51** [OctoPrint/OctoPrint-FirmwareUpdater#303]
**Hardware Setup**
N/A

**Describe the problem**
Firmware updater id logging identical logs as Software updater!

**Log Files**
[octoprint-logs.zip](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/8171095/octoprint-logs.zip)

**Additional context**
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/ad6bd0134ab48494807ceb40e668ba9a24bd0596/octoprint_firmwareupdater/__init__.py#L76

**Comment by benlye** [comment]
Oops.  That's been there a loooong time - since before I inherited the plugin.  Will be fixed in the next release.
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/commit/a0fb8cc93851e89733f2a24b14d1ed89e3323b0d

**Comment by benlye** [comment]
Fixed in v1.13.2
