### ISSUE TITLE
your guide is missing a path statment. in  your firmware updater , for exsample /usr/bin/dfu-util  will show the path is invail when you chick the test button. thats because your missing the path statment. when you login into your pi you need to add PATH=$PATH: /usr/bin/dfu-util for the firmware updater  to vaildate the path. this will be true for the other firmware paths. PATH=$PATH:/your firmeware path

### ISSUE THREAD

**Issue by blade359** [OctoPrint/OctoPrint-FirmwareUpdater#304]
**Hardware Setup**
Please board type and printer make and model.

**Describe the problem**
Please provide a clear and concise description of what the problem is, including details of any error messages you receive (screenshots are helpful).

**Log Files**
Attach the OctoPrint log and the Firmware Updater log Log files, which can be accessed under **Settings** -> **Logging** in OctoPrint, or in `~/.octoprint/logs/` on the host.  Both `octoprint.log` and `~/.octoprint/logs/plugin_firmwareupdater_console.log` should be included.

**Additional context**

**Comment by benlye** [comment]
No, that's not the way it works. There's no need to modify the path at all.
