### ISSUE TITLE
Error when configuring Firmware Updater

### ISSUE THREAD

**Issue by andraisr** [OctoPrint/OctoPrint-FirmwareUpdater#305]
**Hardware Setup**
ATmega2560

**Describe the problem**
Path to avrdude "/usr/bin/avrdude" comes up with the following error "The path doesn't exist"

**Log Files**
Attach the OctoPrint log and the Firmware Updater log Log files, which can be accessed under **Settings** -> **Logging** in OctoPrint, or in `~/.octoprint/logs/` on the host.  Both `octoprint.log` and `~/.octoprint/logs/plugin_firmwareupdater_console.log` should be included.

**I attached the OctoPrint log. The Firmware updater log had nothing in it.**

**Additional context**
[octoprint-logs.zip](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/8189884/octoprint-logs.zip)
![octo fw updater error](https://user-images.githubusercontent.com/23313463/156865695-170ea761-b7f7-49ed-a39f-609fb0697792.jpg)

**Comment by andraisr** [comment]
This is on a new install of the Octoprint to move to Python 3 from the image file.

**Comment by benlye** [comment]
Did you follow the instructions and install avrdude?

https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/avrdude.md#avrdude-installation
