### ISSUE TITLE
After update to Octoprint 1.8.1 the plugin doesn't delete previous flashed firmware

### ISSUE THREAD

**Issue by mriscoc** [OctoPrint/OctoPrint-FirmwareUpdater#314]
With Octoprint < 1.8 when a new firmware is going to be flashed, the plugin takes care of deleting the previously flashed binary.

Printer: Ender 3V2
Current Marlin Bugfix
Marlin Binary File Transfer

**Comment by benlye** [comment]
Most likely cause is that filename that the plugin has for the last-flashed file is out of sync with the files on the SD card.  Can you try manually removing all old firmware files from the card and then flashing a couple more times?

If it still doesn't work I need to see the logs from the plugin, spanning a couple of flash attempts.

**Comment by mriscoc** [comment]
Hi, I already tried deleting all the bin files, also, I can remove the files manually using the M30 G-code.  The plugin can rename the bin files to FW######.bin.
Maybe there could be a permission access problem to write the old used filename. I will check the logs.

**Comment by benlye** [comment]
I think I've found the problem.  Will have a new version for you to test shortly.

**Comment by benlye** [comment]
Please try v1.13.3b1 from the development release channel.

**Comment by mriscoc** [comment]
It is ok now, thank you.

**Comment by benlye** [comment]
v1.13.3 released
