### ISSUE TITLE
Baudrate selection

### ISSUE THREAD

**Issue by Manichee** [OctoPrint/OctoPrint-FirmwareUpdater#32]
This is more of a suggestion/enhancement. I recently installed this on octoprint on a raspberry pi connected to an Anet A8. I couldn't get this working until I created /home/pi/.avrduderc with the baud rate 57600 set. Once I did this, I was successful using the plugin. It would be great if there was either a drop down list or a text entry to put the baudrate and pass it to the flash command using -b baudrate.

**Comment by Manichee** [comment]
So I see this has been implemented in a pull request.

**Comment by benlye** [comment]
Merged #31 which adds baud rate in Advanced Settings
