### ISSUE TITLE
MKS Gen 1.3 panic: runtime error

### ISSUE THREAD

**Issue by SandrRu** [OctoPrint/OctoPrint-FirmwareUpdater#320]
**Hardware Setup**
OrangePi PC + MKS Gen 1.3

**Describe the problem**
Try to flash witch next settings:
HEX compiled in Arduino 1.8.19 (direct flash works fine)
Plugin Settings: 
Board - Arduino Mega
Processor ATmega 2560

**Log Files**
[error.txt](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/9086612/error.txt)
[octoprint-logs.zip](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/9086645/octoprint-logs.zip)
and no firmware update logs 

**Additional context**

**Comment by benlye** [comment]
This plugin is Firmware Updater.  You seem to be trying to use a plugin called [Marlin Flasher](https://github.com/Renaud11232/OctoPrint-Marlin-Flasher).
