### ISSUE TITLE
Octopus v1.1 board

### ISSUE THREAD

**Issue by WesMcGee68** [OctoPrint/OctoPrint-FirmwareUpdater#328]
Is the Octopus v1.1 board updatable using this plug in????

**Comment by benlye** [comment]
It's another STM32-based BigTreeTech board that is updated by copying a file named firmware.bin to the SD card, so you probably can.  

You should try either the [lpc176x](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md) or [marlinbft](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/marlinbft.md) methods.
