### ISSUE TITLE
Add warning about MEATPACK in lpc176x and marlinbft docs.

### ISSUE THREAD

**Issue by JWSmythe** [OctoPrint/OctoPrint-FirmwareUpdater#332]
**Hardware Setup**
BTT SKR 1.4 Turbo (LPC1769) - Ender 3 customized
OctoPrint 1.8.6
Firmware Updater 1.13.3
MeatPack 1.5.21

**Describe the problem**
Add warning about MEATPACK to lpc176x and marlinbft doc.  It must be disabled, at least for marlinbft.  Probably lpc176x also.

https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/lpc176x.md
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/marlinbft.md

**Log Files**
N/A

**Additional context**
Not a problem, just something to add to the docs.  I just tried getting this working.  I didn't get the lpc176x method to work.   I was confident it was something conflicting with my many other Marlin customizations, but I couldn't find what. 

I switched over to the marlinbft method.  When following those instructions, after step 3.i. (Enable Binary File Transfer), "#define BINARY_FILE_TRANSFER", it threw this compile time error:

#error "Either enable MEATPACK_ON_SERIAL_PORT_* or BINARY_FILE_TRANSFER, not both."

Obviously it's spelled out in the error for marlinbft.  I suspect this was my problem with lpc176x. 

Please add a warning in those docs, something like:

```
Please be sure to comment out both MEATPACK_ON_SERIAL_* lines in Configuration_adv.h, 
and disable the meatpack plugin at OctoPrint Settings -> Plugin Manager -> MeatPack   
It will interfere with sending the firmware, and your updates will fail.

//#define MEATPACK_ON_SERIAL_PORT_1
//#define MEATPACK_ON_SERIAL_PORT_2

```
Maybe add a check in the plugin's config, at the Prerequisite Status, where you're already checking BINARY_FILE_TRANSFER and marlin-binary-protocol.

No response necessary, mine is working now.

Thank you for your work on this updater plugin.  I make a lot of changes to my firmware, and it is really annoying to move the SD card repeatedly while tuning and testing.

**Comment by benlye** [comment]
I've updated the docs for MarlinBFT.  MEATPACK doesn't affect LPC1768 (confirmed on my printer).
