### ISSUE TITLE
"Unable to transfer Firmware file to printer" Flashing method: marlinbft

### ISSUE THREAD

**Issue by dlopez408** [OctoPrint/OctoPrint-FirmwareUpdater#333]
**Hardware Setup**
RockPi 4b+ & Longer LK1

**Describe the problem**
I am "unable to transfer firmware file to printer" using the marlinbft flash method. I have all prerequisites installed and enabled. I am not sure what the issue is.

 **I apologize if there is an obvious solution to this problem, I am still learning.**

![image](https://user-images.githubusercontent.com/70249076/214709273-a74bc7fb-d43d-4429-ade9-d8884e87a44e.png)

**Log Files**
[octoprint.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/10504343/octoprint.log)

**Additional context**
I am trying to use the plugin for the first time. I have just installed it today.

**Comment by w7boz** [comment]
This may be totally wrong. But have you tried a different baud rate? Maybe 115200?

**Comment by benlye** [comment]
```
2023-01-25 14:40:05,776 - octoprint.plugins.firmwareupdater - INFO - Transfering file to printer using Marlin BFT '/tmp/tmpuzcyoxo2' -> /firmware.bin
2023-01-25 14:40:05,818 - octoprint.plugins.firmwareupdater - ERROR - Flashing failed. Unable to transfer file.
Traceback (most recent call last):
  File "/home/dlo/OctoPrint/lib/python3.8/site-packages/octoprint_firmwareupdater/methods/marlinbft.py", line 105, in _flash_marlinbft
    filetransfer.copy(firmware, target, True, False)
  File "/home/dlo/OctoPrint/lib/python3.8/site-packages/binproto2/protocols.py", line 407, in copy
    self.open(dest_filename, compression_support, dummy)
  File "/home/dlo/OctoPrint/lib/python3.8/site-packages/binproto2/protocols.py", line 372, in open
    raise Exception("Cannot open file on client")
Exception: Cannot open file on client
```

I don't think it's a baud rate problem - the BFT protocol is connected and synced. `Cannot open file on client` means that the protocol was not able to create the target file on your printer.  

Try going into the plugins options and enabling the `Verbose file transfer progress logging` option (it's on the 'Advanced 2' tab.  Try to flash again and then upload the log.  It may not tell us exactly what's going on, but it's worth trying.

Otherwise, it's possibly a combination of the SD card settings in your Marlin config.

**Comment by dlopez408** [comment]
Thanks for the replies! I will update with the new log soon

**Comment by dlopez408** [comment]
Here is the log with the `Verbose file transfer progress logging` option enabled

[octoprint verbose.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/10710401/octoprint.verbose.log)

**Comment by benlye** [comment]
Not much I can do to help with this - the protocol can't open the destination file on your printer. The binary file protocol is written and maintained by someone else.
