### ISSUE TITLE
FEATURE REQUEST: Enable updater to find and read zip'ed files

### ISSUE THREAD

**Issue by puterboy** [OctoPrint/OctoPrint-FirmwareUpdater#335]
Prusa at least distributes its firmware in Zip'ed files.
It would save a step if the module could recognize and read Zip files (two steps if you then want to come back and delete the uncompressed version after updating)
This shouldn't be too hard as Zip is a well-known standard with plenty of tools to read.

Thanks

**Comment by benlye** [comment]
Can you upload (or point me at) an example of a zip file? Is the file inside always named the same? Is there only one file inside, or are there multiple files? If it's a zip file containing one bin file (or if the firmware bin file always has the same name) then it shouldn't be too hard.

**Comment by puterboy** [comment]
It's just a compressed Zip of a folder that contains a single (uncompressed) folder with the same name that in turn contains one .hex firmware file plus a couple of pdfs.

```
$ unzip -l prusa3d_fw_3_12_1_MK3S.zip
Archive:  prusa3d_fw_3_12_1_MK3S.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2023-01-23 08:21   prusa3d_fw_3_12_1_MK3S/
   935909  2023-01-16 05:53   prusa3d_fw_3_12_1_MK3S/Firmware_upgrade_guide_CS.pdf
   947775  2023-01-16 05:53   prusa3d_fw_3_12_1_MK3S/Firmware_upgrade_guide_DE.pdf
   951528  2023-01-16 05:54   prusa3d_fw_3_12_1_MK3S/Firmware_upgrade_guide_ENG.pdf
   947239  2023-01-16 05:54   prusa3d_fw_3_12_1_MK3S/Firmware_upgrade_guide_ES.pdf
   947675  2023-01-16 05:54   prusa3d_fw_3_12_1_MK3S/Firmware_upgrade_guide_FR.pdf
   946434  2023-01-16 05:54   prusa3d_fw_3_12_1_MK3S/Firmware_upgrade_guide_IT.pdf
  1528209  2023-01-16 05:54   prusa3d_fw_3_12_1_MK3S/Firmware_upgrade_guide_PL.pdf
  1048002  2023-01-23 08:19   prusa3d_fw_3_12_1_MK3S/prusa3d_fw_MK3S_MK3S+_3_12_1_5686.hex
---------                     -------
  8252771                     9 files
```

Here is the download site: https://help.prusa3d.com/downloads

**Comment by puterboy** [comment]
Couldn't you just do the equivalent of unzip -l to identify the hex
file and then just unzip & unload that file?

Ben Lye wrote at about 02:33:37 -0800 on Wednesday, February 1, 2023:

**Comment by benlye** [comment]
No, that's not how it works when the browser uploads a file. There's really no way to do it on the client side or in the browser.
