### ISSUE TITLE
Ender 5 Plus questions

### ISSUE THREAD

**Issue by jle2199** [OctoPrint/OctoPrint-FirmwareUpdater#344]
**Hardware Setup**
Ender 5 plus with Creality v2.2 board

**Describe the problem**
How do I use the plugin to install firmware to my board? I can not determine the MCU

**Additional context**
I'm a bit of a luddite and appreciate any help.

**Comment by benlye** [comment]
Most Creality boards use an Atmega 1284p.  Follow the instructions [here](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/doc/avrdude.md) to configure the plugin.

Once the plugin is configured, flashing firmware is a simple operation:

1. Select the COM port to communicate with the board
2. Select a firmware file, either located on the filesystem or via a URL
3. Click the appropriate Flash from button
4. Wait for the firmware update to complete

Beyond that, your best bet for help is probably a user group for your specific printer.
