### ISSUE TITLE
{disableverify} does not get replaced by space or -v if it is the last thing on the command line

### ISSUE THREAD

**Issue by cdsmith69** [OctoPrint/OctoPrint-FirmwareUpdater#351]
The {disableverify} parameter should be replaced by either -v or by a space, depending on the check box for "Disable write verification."  But if it is the last thing on the command line the text {disableverify} is left unchanged in the command line that is called.

I believe this may be because of the trailing spaces in the replace commands in bossac.py:

    if bossac_disableverify:
        bossac_command = bossac_command.replace(" {disableverify} ", " ")
    else:
        bossac_command = bossac_command.replace(" {disableverify} ", " -v ")

If {disableverify} is the last thing on the command line the trailing space does not exist and the replace doesn't happen.

The context here is that I have a device that requires a more complicated flashing process than just one call to bossac, so I thought I would just put a shell script on the Raspberry Pi called proflash.sh that does the multiple steps I need, and run that script with the command line  /home/pi/proflash.sh {bossac} {port} {firmware} {disableverify} instead of the usual bossac command line.  But my script was getting "{disableverify}" instead of a space or -v.  Flipping the order to /home/pi/proflash.sh {bossac} {port} {disableverify} {firmware} fixes the issue and the script gets the proper space or -v in place of {disableverify}.

**Comment by benlye** [comment]
Good catch, I'll take care of it.

**Comment by bhuliu** [comment]
Good catch！！！
——————————————————
[Steppermotor](https://www.steppermotor.fr) provides a variety of different types of gear reducers including planetary reducers, parallel shaft reducers, and worm reducers.

**Comment by benlye** [comment]
Resolved in 1.14.1
