### ISSUE TITLE
Feature Request: Backup and restore Marlin settings before and after update

### ISSUE THREAD

**Issue by JoveToo** [OctoPrint/OctoPrint-FirmwareUpdater#357]
Hi,

Simple feature: add an option to back up the Marlin settings before the update and restore them afterwards.

**Comment by JoveToo** [comment]
Bump

**Comment by benlye** [comment]
I don't think I'm going to do this. Backing up might be simple but restoring is unlikely to be easy between versions when configuration options may change.

Plus, there are [other plugins](https://plugins.octoprint.org/plugins/eeprom_marlin/) that already do this, so I don't really see the point in doing it in this one.
