### ISSUE TITLE
Please allow avrdude 'stk500v2' protocol

### ISSUE THREAD

**Issue by coldtobi** [OctoPrint/OctoPrint-FirmwareUpdater#36]
I need this avrdude line to programm:
avrdude -D -patmega2560 -P/dev/ttyUSB0 -cstk500v2 -b115200 -Uflash:w:applet/Marlin.hex:i

Would be great if one could select the "stk500v2" or have a manual entry field for overrides

Thanks!

**Comment by benlye** [comment]
Yep, can do - I have a big update to push out in the next day or so so I'll include this too.

**Comment by coldtobi** [comment]
just made a pull request :)

**Comment by benlye** [comment]
Just released 1.0.0 with the stk500v2 programmer as an option.
