### ISSUE TITLE
heatshrink deprecation and replacement

### ISSUE THREAD

**Issue by marioeyoung** [OctoPrint/OctoPrint-FirmwareUpdater#360]
**Hardware Setup**
N/A

**Describe the problem**
Heatshrink has been deprecated according to this thread:

 https://github.com/johan-sports/pyheatshrink/issues/17

Please update to the better maintained version.

**Log Files**
N/A

**Additional context**

https://github.com/eerimoq/pyheatshrink

**Comment by jneilliii** [comment]
Check this comment. The issue is in a module dependency, not within the plugin code itself.
