### ISSUE TITLE
Support for Prusa MK3.5

### ISSUE THREAD

**Issue by timur-tabi** [OctoPrint/OctoPrint-FirmwareUpdater#363]
I have a Prusa MK3 upgrade to an MK3.5.  It appears that this plugin is incompatible with the MK3.5 (and later) control boards.  Is it possible to add support?

**Comment by benlye** [comment]
I don't have the printer or the board so cannot say. 

- How is it updated normally?
- Can you put a firmware on it which exposes the SD card (assuming it has one) to a USB-connected host?

**Comment by snitkofb** [comment]
The files changed format from .hex to .bbf  which doesn't appear compatible with the extension.

**Comment by benlye** [comment]
The firmware updater plugin doesn't care about file format, other than filtering the list of files which can be selected. The filter can be disabled with this setting:

<img width="430" alt="image" src="https://github.com/user-attachments/assets/4366d708-db3a-4a8f-87f5-f7f8ef76f289">
