### ISSUE TITLE
Please add way to pass on command line arguments to uploader

### ISSUE THREAD

**Issue by nionio6915** [OctoPrint/OctoPrint-FirmwareUpdater#40]
It would be nice if we could add command line options to the uploader command string.  

In my case, using avrdude, I would like the verbosity levels as a configurable option in the user interface so more info is in the log when flashing.

**Comment by benlye** [comment]
Pretty straightforward request - I'll get it done shortly.

**Comment by Stady234** [comment]
Just wondering if this ever was completed?

**Comment by benlye** [comment]
Done in v1.2.0 - under advanced settings you can completely edit the command line.
