### ISSUE TITLE
Install AVRDude from interface

### ISSUE THREAD

**Issue by edwinm** [OctoPrint/OctoPrint-FirmwareUpdater#44]
Many people are not comfortable with the terminal and command line.

Can't you make an "Install AVRDude" button?

**Comment by jhgreen215** [comment]
I'm not sure if this warrants its own issue, but I am having trouble installing AVRDude on a fresh install of OctoPi, even after `apt-get update && apt-get upgrade`

Maybe this feature would help?

**Comment by benlye** [comment]
I don't think I want to do this.  Sure, it would probably be easy enough on a Pi, but not everyone uses that platform, and the installation can vary by distribution.  Also, if the installation has issues when you try to do it manually on a freshly-installed OctoPi, running the same commands by a button click is unlikely to be successful.
