### ISSUE TITLE
Feature request - Support for GT2560 board

### ISSUE THREAD

**Issue by vlad1212** [OctoPrint/OctoPrint-FirmwareUpdater#55]
Would be cool if this plugin supported Geeetech GT2560 board. Thanks

**Comment by benlye** [comment]
GT2560 is simply an atmega2560 board - have you tried it with `Atmega2560` as the MCU and `wiring` as the programmer?  You may have to experiment with the baud rate,

**Comment by vlad1212** [comment]
That's what I thought. Tried every possible setting, but keep getting time out error.

**Comment by vlad1212** [comment]
Hey, I set baud rate to default and it worked! Thanks
