### ISSUE TITLE
RADDS serial issue

### ISSUE THREAD

**Issue by unf0rg0tt3n** [OctoPrint/OctoPrint-FirmwareUpdater#56]
Hi,

I have an issue connecting my RADDS to octopi with serial connection.
Uploading the repetier firmware from my laptop wasn't an issue, everything worked fine.
But when I wanted to start the printer connection with octopi it won't work.

[serial(2).log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/2343357/serial.2.log)

I have attached the serial log.

Thanks in common

**Comment by benlye** [comment]
Not really enough info here for me to be able to help.  Is this still a problem?  If I don't hear anything I'll close the issue in a few days.
