### ISSUE TITLE
Anet flash generating an error

### ISSUE THREAD

**Issue by banichow** [OctoPrint/OctoPrint-FirmwareUpdater#57]
Sorry to bother, I am trying to use the plugin and it is generating:

Avrdude says: 'not in sync: resp=0x73

I have the correct port and the software is installed. It is an Anet 1.0 board. Works good from the PC. I looked on the Octoprint discourse site and did not find much. Below is the screen shots.

Thanks 

![untitled-1](https://user-images.githubusercontent.com/32231334/45268167-57e2ec80-b446-11e8-8ce5-98529737536e.png)
![untitled-2](https://user-images.githubusercontent.com/32231334/45268170-5ca7a080-b446-11e8-83ac-e83cc06a7faf.png)

**Comment by benlye** [comment]
The plug-in definitely works with the Anet board - I've flashed mine many times.  Try changing baud rate setting to 57600, 115200, or even 2500000.

**Comment by banichow** [comment]
Thanks for the information, I will try again. I have it set to 115200 and this works for standard gcode. Does OctoPrint have to be "Connected" to the printer?

**Comment by benlye** [comment]
No, OctoPrint doesn't need to be connected - the plugin will just disconnect if it is.

**Comment by zak062** [comment]
I was having the same issue as Banichow with a Alunar M505 (anet a8 clone). I changed the baud rate to 57600 and was able to flash the firmware. Thanks you benlye!
