### ISSUE TITLE
"automatic updates check" ?

### ISSUE THREAD

**Issue by psy0rz** [OctoPrint/OctoPrint-FirmwareUpdater#59]
I assumed this meant it will check automaticly if there are updates for your printer? How does this work? I dont see anything about this anywhere in the config?

**Comment by benlye** [comment]
The original author of the plugin wrote a proprietary update check system which was later removed.  

@foosel, could you update the Github repo description?  Maybe this?

> OctoPrint plugin for flashing pre-compiled firmware images to a 3D printer. See https://plugins.octoprint.org/plugins/firmwareupdater/

**Comment by foosel** [comment]
@benlye done. Also gave you Admin rights which for some reason I hadn't yet.

And sorry for the delay, was on an overdue vacation.
