### ISSUE TITLE
wont upload if printer is connected to port "AUTO"

### ISSUE THREAD

**Issue by TylonHH** [OctoPrint/OctoPrint-FirmwareUpdater#6]
Hi,
I know its simple to solve, because I just have to select the only one port. Just wanna mentioned it here.

**Comment by foosel** [comment]
I think this should be solved in the version currently on `devel`/0.2.0, which has been heavily refactored to get rid of the more or less proprietary update mechanism that was also the reason this plugin never got published to the repository.

**Comment by benlye** [comment]
Fixed by #16.
