### ISSUE TITLE
Starting flash... over and over again. CH340

### ISSUE THREAD

**Issue by Zicmu69** [OctoPrint/OctoPrint-FirmwareUpdater#66]
Hello. I can't flash my firmware. I'm using Arduino mega clone with CH340 chip onboard- could that be a problem?. After set everything up it keeps "Starting flash..." prompt forever.

**Comment by benlye** [comment]
Can you post the firmware updater and OctoPrint log files?

**Comment by Zicmu69** [comment]
[plugin_firmwareupdater_console.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/2660957/plugin_firmwareupdater_console.log)


[octoprint.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/2660963/octoprint.log)

**Comment by benlye** [comment]
Check the path to avrdude - do you have it set to `/usr/bin/avrdude`?

If that doesn't work please retrieve and send the logs again - the OctoPrint log you've attached does not cover the same time period as the plugin log, and does not seem to contain an attempt to update the firmware.

**Comment by Zicmu69** [comment]
Patch to avrdude is valid. Test prove it.
Here are latest logs with two attempts. I need to reboot my PI before second attempt, couse "already flashing" window pops out if I not.

[octoprint.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/2672463/octoprint.log)
[plugin_firmwareupdater_console.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/2672464/plugin_firmwareupdater_console.log)

**Comment by benlye** [comment]
The avrdude path test is not always working, see #65.  If it's not set to `/usr/bin/avrdude` please do so - the leading slash is important.

**Comment by Zicmu69** [comment]
TRUE!
I had usr/bin/avrdude in my settings. No way it was that easy... Flashing lika a charm! No more box opening to play with my firm!

Thank you so so much @benlye

**Comment by benlye** [comment]
v1.1.0 released which improves the path tests.
