### ISSUE TITLE
Un-set value in extras/firmwareupdater.md = log errors

### ISSUE THREAD

**Issue by OutsourcedGuru** [OctoPrint/OctoPrint-FirmwareUpdater#68]
## Low priority log error:

In the file [extras/firmwareupdater.md](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/d9265448de28df63049c2695ed0dca905df7238b/extras/firmwareupdater.md), one of the screenshot variables is still the default as created from the cookie-cutter.

This results in odd `octoprint.log` reporting of:

```
2018-12-11 15:17:41,694 - tornado.access - WARNING - 404 GET /url%20of%20a%20featured%20image%20for%20your%20plugin,%20/assets/img/... (xx.xx.xx.xx) 17.61ms
```

**Comment by benlye** [comment]
Thanks.  I've deleted the template files and will make a new release soon.
