### ISSUE TITLE
Upgrade Anet A8 from SkyNet to Marlin

### ISSUE THREAD

**Issue by Wimpie1000** [OctoPrint/OctoPrint-FirmwareUpdater#78]
Hi there. Has anyone upgraded their Anet from Skynet to Marlin with this plugin? If I configure and save the setting as shown in the picture below, do I need to upload a certain file, like if you go the Arduino Route you use the configuration.h file for Anet?

![Untitled](https://user-images.githubusercontent.com/28179781/54532253-00db4880-4990-11e9-823a-5052bea8e8f6.jpg)

**Comment by benlye** [comment]
Yes, you can do that with this plugin.  You need to download Marlin, customize the configuration file (starting with the Anet A8 example), compile the firmware, then upload the resulting .hex file using the plugin.
