### ISSUE TITLE
[Help] Trying to configure settings for Ender 3/Melzi board

### ISSUE THREAD

**Issue by NovaViper** [OctoPrint/OctoPrint-FirmwareUpdater#83]
I'm trying to setup a configuration that works with the Ender 3 before trying to flash it. Normally within the Audrunio IDE, it's a board configuration of Sanguino (1284p) and the AVR Programmer is AVRISP MKII. How can I setup the same configuration with the plugin?

**Comment by benlye** [comment]
Choose Atmega1284p as the MCU and stk500v2 as the programmer.

![ender](https://user-images.githubusercontent.com/23322579/56111577-651e0780-5f50-11e9-8333-5d7a7fd08e25.jpg)

In a future update I'll rename 'stk500v2' to 'AVRISP MKII' to make it obvious that they are the same thing.

**Comment by NovaViper** [comment]
Thanks for the info! Hey, do you know how I can compile the Marlin firmware to upload?

**Comment by NovaViper** [comment]
It doesn't work, it says timeout with programmer <_>

**Comment by benlye** [comment]
Please attach the logs. Must likely you are using the incorrect settings for your board.

https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/README.md#troubleshooting

**Comment by NovaViper** [comment]
Sorry about that! Here ya go: 
[plugin_firmwareupdater_console.log](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/files/3096189/plugin_firmwareupdater_console.log)

**Comment by benlye** [comment]
A quick Google says that an Ender 3 needs a bootloader installed before it can be flashed. Have you done that?

Sorry, but this is a printer board I have no experience with. You're probably better off trying to find a Facebook group or other community who can help you to get started.

There also seem to be multiple YouTube videos available. Once you can flash the printer from the Arduino IDE you should be able to use the plugin without problems.

**Comment by NovaViper** [comment]
I did flash a boot loader onto the printer, which is even stranger as to why it doesn't work with the plugin

**Comment by benlye** [comment]
Are you able to flash it from the Arduino IDE? Can you post the settings you use in the IDE?

**Comment by NovaViper** [comment]
I am able to upload through the IDE, these are the settings

Board: Sanguino
Processor: ATmega1284 or ATmega1284p (16hz)
Programmer: AVRISP mkII

**Comment by NovaViper** [comment]
This is also the command used by the IDE: -CC:\Users\user\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino14/etc/avrdude.conf -v -patmega1284p -carduino -PCOM5 -b115200 -D -Uflash:w:C:\Users\user\AppData\Local\Temp\arduino_build_474603/Marlin.ino.hex:i

**Comment by benlye** [comment]
Yeah, use 'arduino' as the programmer on the plugin, as that's what the IDE is using.

**Comment by benlye** [comment]
> This is also the command used by the IDE: -CC:\Users\user\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino14/etc/avrdude.conf -v -patmega1284p **-carduino** -PCOM5 -b115200 -D -Uflash:w:C:\Users\user\AppData\Local\Temp\arduino_build_474603/Marlin.ino.hex:i

To be a little more helpful (sorry, I've been on my mobile the last few days, so more terse than normal)...

The Programmer that you have selected in the Arduino IDE is only used when you choose 'Upload via Programmer'.  When you choose 'Upload' it uses the default programming method for the selected MCU.  You can see in your IDE command line that it is using 'arduino' as that is the '-c' option: `-carduino` .

You don't really have an 'AVRISP MKII' programmer, so there is no use selecting that in the plugin, and it won't work.

In the plugin you should choose board as 'atmega1284p' and programmer as 'arduino' and it *should* work.  If it still doesn't work, upload the firmware updater's log file again.

**Comment by NovaViper** [comment]
That fixed it! Thanks 😄
