### ISSUE TITLE
USB Mount Usb naming

### ISSUE THREAD

**Issue by hhoweson** [OctoPrint/OctoPrint-FirmwareUpdater#90]
It would appear that with the latest version of USB mount the first usb drive detected is now called media/usb0 rather than media/usb, the documentation should be updated accordingly

**Comment by hhoweson** [comment]
I opened this issue because the usb mount conf file seemed to suggest that the first usb would be named usb0 however despite this it is still named usb so please ignore this post

**Comment by benlye** [comment]
Actually your right in both ways.  The mount point is /media/usb0, but this is sym-linked to /media/usb.

**Comment by hhoweson** [comment]
Ahhhhh, I see, that explains it. Thanks for clarifying and thanks for the amazing plugin!
