### ISSUE TITLE
USB_SD_ONBOARD is now SDCARD_CONNECTION ONBOARD

### ISSUE THREAD

**Issue by thisiskeithb** [OctoPrint/OctoPrint-FirmwareUpdater#93]
This is not so much an issue, but an FYI. 

https://github.com/MarlinFirmware/Marlin/commit/064177154ce7912293efa67c7e0dfcaa4a7301ec changes `USB_SD_ONBOARD`to `SDCARD_CONNECTION ONBOARD`.

**Comment by benlye** [comment]
Thanks!  Doc updated.

**Comment by Silithas** [comment]
Onboard doesn't work for me. Ender 3 pro with skr 1.3 with 2209 drivers. I click init media, and nothing happens.
