### ISSUE TITLE
LPC1768 use model

### ISSUE THREAD

**Issue by marclefevre** [OctoPrint/OctoPrint-FirmwareUpdater#99]
I have a Bigtreetech SKR 1.3 (using LPC1768) that seems to be supported. If I configure the settings for that and try an update, the plugin throws an error that it's not configured. I don't know where else to configure it.
Does the update consist of copying the firmware file to the SD card that the controller presents to octoprint?

**Comment by benlye** [comment]
Yes, that's pretty much how it works.

Can you attach a screenshot of your plugin settings?

**Comment by marclefevre** [comment]
![configuration](https://user-images.githubusercontent.com/29385573/62167624-4702ca00-b2e9-11e9-92a8-61f1a9aed6a6.png)
![ready to flash](https://user-images.githubusercontent.com/29385573/62167631-49fdba80-b2e9-11e9-8ce6-1b6ebfa296a0.png)
![failure](https://user-images.githubusercontent.com/29385573/62167641-4c601480-b2e9-11e9-898b-aa644269a301.png)

**Comment by benlye** [comment]
You have specified a serial port where you should have put the path to the SD card mount point.
![setting](https://user-images.githubusercontent.com/23322579/62191969-a229d080-b36c-11e9-81f9-0262cb457b12.png)

If you followed the [LPC1768 instructions ](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/master/README.md#lpc1768-boards)and installed USBmount, the path should be `/media/usb`, **not** `/dev/ttyACM0`.

**Comment by marclefevre** [comment]
OK.  Thanks for the pointer.  I mistakenly assumed that the process was simple enough that there were no instructions.  I followed them and have usbmount installed.  I have gotten the reset failed error and am working on getting the latest Marlin.
One suggestion I might make is to detect an attempt to set the folder to a device file and, rather than confirm it's valid, point out that it needs to be a directory.
Thanks for all of the help.

**Comment by benlye** [comment]
> One suggestion I might make is to detect an attempt to set the folder to a device file and, rather than confirm it's valid, point out that it needs to be a directory.

Fixed in v1.6.1.
